In [1]:
import numpy as np
import pandas as pd

In [2]:
def quality_report(data):

    """This method will do a basic data quality report for a data frame"""
        
    if (type(data) != pd.core.frame.DataFrame):
        raise TypeError("Data must be pandas.core.frame.DataFrame")
    else: 
        columns = list(data.columns.values)
        data_type = pd.DataFrame(data.dtypes, columns=['Data type'])
        missing_data = pd.DataFrame(
        data.isnull().sum(), columns=['missing values'])
        present_data = pd.DataFrame(data.count(), columns=['present values'])
        unique_values = pd.DataFrame(columns=['unique values'])
        minimum_values = pd.DataFrame(columns=['minimum values'])
        max_values = pd.DataFrame(columns=['maximun values'])
        
        for i in columns:
            unique_values.loc[i] = [data[i].nunique()]
            try:
                minimum_values.loc[i] = [data[i].min()]
                max_values.loc[i] = [data[i].max()]
            except:
                pass
        
        DQ_report = data_type.join(missing_data).join(present_data).join(
        unique_values).join(minimum_values).join(max_values)
    
    return DQ_report

In [3]:
csv_original = 'DataSetNike.csv'
dataset_original = pd.read_csv(csv_original, encoding='latin-1', low_memory=False)
dataset_original

,Store,Date,No_Tran,UPC,Material,Size,Division,Global Category,Gender,Public Price,Units,Sale Price Wo tax,Tax,Sale Price,Discount,Promo,Sales Type,Emp No,Sales Man,TTL Cost
0,TIENDA 1,9/1/2017 0:00,45372,9.120108e+10,146124-VQD,L,APPAREL,NIKE SPORTSWEAR,MENS,349.0,1,150.431035,24.068966,174.50,174.50,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,357477,106.418005
1,TIENDA 1,9/1/2017 0:00,52913,9.120120e+10,662009-ZQH,L,APPAREL,NIKE SPORTSWEAR,MENS,349.0,1,210.603448,33.696552,244.30,104.70,TIERED PROMOTION VALUE 30P OFF,4 - PROMOTION,NaN,274702,106.418005
2,TIENDA 1,9/1/2017 0:00,58648,9.120137e+10,990552-HCP,5.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,999.0,1,516.724138,82.675862,599.40,399.60,TIERED PROMOTION VALUE 40P OFF,4 - PROMOTION,NaN,340843,299.220506
3,TIENDA 1,9/1/2017 0:00,58659,9.120137e+10,990552-HCP,5.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,999.0,1,430.603448,68.896552,499.50,499.50,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,340843,299.220506
4,TIENDA 1,9/1/2017 0:00,58658,9.120137e+10,990552-HCP,5.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,-599.4,-1,-516.724138,-82.675862,-599.40,0.00,,2 - RETURNS,NaN,340843,-299.220506
5,TIENDA 1,9/1/2017 0:00,58610,9.120137e+10,990552-HCP,6.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,999.0,1,861.206897,137.793103,999.00,0.00,,1 - NORMAL,NaN,340843,299.220506
6,TIENDA 1,9/1/2017 0:00,52924,9.120137e+10,990552-HCP,6.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,999.0,1,482.275862,77.164138,559.44,439.56,TIERED PROMOTION VALUE 20P OFF,5 - EMPLOYEE DISCOUNT,338083,274702,299.220506
7,TIENDA 1,9/1/2017 0:00,52846,9.120137e+10,990552-HCP,7.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,999.0,1,301.422414,48.227586,349.65,649.35,TIERED PROMOTION VALUE 50P OFF,5 - EMPLOYEE DISCOUNT,185634,274702,299.220506
8,TIENDA 1,9/1/2017 0:00,52846,9.120141e+10,662014-IQQ,M,APPAREL,NIKE SPORTSWEAR,WOMENS,249.0,1,75.129310,12.020690,87.15,161.85,TIERED PROMOTION VALUE 50P OFF,5 - EMPLOYEE DISCOUNT,185634,274702,98.535730
9,TIENDA 1,9/1/2017 0:00,58690,9.120150e+10,327277-NNV,S,APPAREL,NIKE SPORTSWEAR,WOMENS,449.0,1,309.655172,49.544828,359.20,89.80,TIERED PROMOTION VALUE 20P OFF,4 - PROMOTION,NaN,340843,171.137170
10,TIENDA 1,9/1/2017 0:00,45397,9.120249e+10,659994-MAU,7,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,-899.4,-1,-775.344828,-124.055172,-899.40,0.00,,2 - RETURNS,NaN,357477,-582.064528
11,TIENDA 1,9/1/2017 0:00,52970,9.120249e+10,659994-MAU,7,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,1499.0,1,1033.793103,165.406897,1199.20,299.80,TIERED PROMOTION VALUE 20P OFF,4 - PROMOTION,NaN,274702,582.064528
12,TIENDA 1,9/1/2017 0:00,45499,9.120254e+10,212577-XEF,XS,APPAREL,NIKE SPORTSWEAR,WOMENS,699.0,1,301.293104,48.206897,349.50,349.50,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,357477,287.652064
13,TIENDA 1,9/1/2017 0:00,58659,9.120254e+10,212577-XEF,S,APPAREL,NIKE SPORTSWEAR,WOMENS,1398.0,2,602.586207,96.413793,699.00,699.00,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,340843,575.304129
14,TIENDA 1,9/1/2017 0:00,58648,9.120254e+10,212577-XEF,S,APPAREL,NIKE SPORTSWEAR,WOMENS,1398.0,2,723.103448,115.696552,838.80,559.20,TIERED PROMOTION VALUE 40P OFF,4 - PROMOTION,NaN,340843,575.304129
15,TIENDA 1,9/1/2017 0:00,45523,9.120254e+10,212577-XEF,S,APPAREL,NIKE SPORTSWEAR,WOMENS,699.0,1,342.258621,54.761379,397.02,301.98,TIERED PROMOTION VALUE 40P OFF,4 - PROMOTION,NaN,357477,287.652064
16,TIENDA 1,9/1/2017 0:00,58658,9.120254e+10,212577-XEF,S,APPAREL,NIKE SPORTSWEAR,WOMENS,-838.8,-2,-723.103448,-115.696552,-838.80,0.00,,2 - RETURNS,NaN,340843,-575.304129
17,TIENDA 1,9/1/2017 0:00,52846,9.120254e+10,212577-XEF,M,APPAREL,NIKE SPORTSWEAR,WOMENS,699.0,1,210.905172,33.744828,244.65,454.35,TIERED PROMOTION VALUE 50P OFF,5 - EMPLOYEE DISCOUNT,185634,274702,287.652064
18,TIENDA 1,9/1/2017 0:00,52937,9.120254e+10,212577-XEF,M,APPAREL,NIKE SPORTSWEAR,WOMENS,699.0,1,482.068966,77.131034,559.20,139.80,TIERED PROMOTION VALUE 20P OFF,4 - PROMOTION,NaN,274702,287.652064
19,TIENDA 1,9/1/2017 0:00,58659,9.120254e+10,212577-XEF,L,APPAREL,NIKE SPORTSWEAR,WOMENS,699.0,1,301.293104,48.206897,349.50,349.50,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,340843,287.652064
20,TIENDA 1,9/1/2017 0:00,58648,9.120254e+10,212577-XEF,L,APPAREL,NIKE SPORTSWEAR,WOMENS,699.0,1,361.551724,57.848276,419.40,279.60,TIERED PROMOTION VALUE 40P OFF,4 - PROMOTION,NaN,340843,287.652064
21,TIENDA 1,9/1/2017 0:00,58658,9.120254e+10,212577-XEF,L,APPAREL,NIKE SPORTSWEAR,WOMENS,-419.4,-1,-361.551724,-57.848276,-419.40,0.00,,2 - RETURNS,NaN,340843,-287.652064
22,TIENDA 1,9/1/2017 0:00,45470,9.120297e+10,163605-LET,9,FOOTWEAR,FOOTBALL/SOCCER,MENS,1199.0,1,413.448276,66.151724,479.60,719.40,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,357477,716.165201
23,TIENDA 1,9/1/2017 0:00,45417,9.120321e+10,660689-PGX,7,FOOTWEAR,NIKE SPORTSWEAR,MENS,-999.5,-1,-861.637931,-137.862069,-999.50,0.00,,2 - RETURNS,NaN,357477,-1020.470576
24,TIENDA 1,9/1/2017 0:00,45391,9.120321e+10,660689-PGX,7,FOOTWEAR,NIKE SPORTSWEAR,MENS,1999.0,1,861.637931,137.862069,999.50,999.50,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,357477,1020.470576
25,TIENDA 1,9/1/2017 0:00,45418,9.120321e+10,660689-PGX,8,FOOTWEAR,NIKE SPORTSWEAR,MENS,999.5,1,861.637931,137.862069,999.50,0.00,,1 - NORMAL,NaN,357477,1020.470576
26,TIENDA 1,9/1/2017 0:00,45390,9.120321e+10,760862-QGY,9,FOOTWEAR,NIKE SPORTSWEAR,MENS,-1199.4,-1,-1033.965517,-165.434483,-1199.40,0.00,,2 - RETURNS,NaN,357477,-1015.662533
27,TIENDA 1,9/1/2017 0:00,52954,9.120365e+10,163518-KCS,6.5,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,849.0,1,731.896552,117.103448,849.00,0.00,,1 - NORMAL,NaN,274702,359.554153
28,TIENDA 1,9/1/2017 0:00,45461,9.120365e+10,163518-KCS,7,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,849.0,1,365.948276,58.551724,424.50,424.50,TIERED PROMOTION VALUE 50P OFF,4 - PROMOTION,NaN,357477,359.554153
29,TIENDA 1,9/1/2017 0:00,52931,9.120365e+10,163518-KCS,8,FOOTWEAR,NIKE SPORTSWEAR,WOMENS,849.0,1,585.517241,93.682759,679.20,169.80,TIERED PROMOTION VALUE 20P OFF,4 - PROMOTION,NaN,274702,359.554153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263657,TIENDA 1,9/30/2018 0:00,26144,8.880000e+11,661984-GQO,S,APPAREL,NIKE SPORTSWEAR,MENS,599.0,1,289.172414,46.267586,335.44,263.56,Store Level Promotion,4 - PROMOTION,NaN,362045,241.582276
263658,TIENDA 1,9/30/2018 0:00,26197,8.880000e+11,661984-GQO,M,APPAREL,NIKE SPORTSWEAR,MENS,599.0,1,289.172414,46.267586,335.44,263.56,Store Level Promotion,4 - PROMOTION,NaN,409947,241.582276
263659,TIENDA 1,9/30/2018 0:00,3142,8.880000e+11,661984-GQO,L,APPAREL,NIKE SPORTSWEAR,MENS,599.0,1,289.172414,46.267586,335.44,263.56,Store Level Promotion,4 - PROMOTION,NaN,269303,241.582276
263660,TIENDA 1,9/30/2018 0:00,689,8.880000e+11,762578-QRY,XL,APPAREL,NIKE SPORTSWEAR,MENS,649.0,1,391.637931,62.662069,454.30,194.70,MX NFS 30P OFF,4 - PROMOTION,NaN,351388,306.476279
263661,TIENDA 1,9/30/2018 0:00,19279,8.880000e+11,215577-STA,XL,APPAREL,NIKE SPORTSWEAR,MENS,549.0,1,331.293103,53.006897,384.30,164.70,MX NFS 30P OFF,4 - PROMOTION,NaN,312652,215.196322
263662,TIENDA 1,9/30/2018 0:00,19263,8.880000e+11,454287-YNG,S,APPAREL,RUNNING,MENS,1099.0,1,606.344828,97.015172,703.36,395.64,Store Level Promotion,4 - PROMOTION,NaN,312652,389.189178
263663,TIENDA 1,9/30/2018 0:00,26200,8.880000e+11,994341-ATI,M,APPAREL,RUNNING,MENS,549.0,1,331.293103,53.006897,384.30,164.70,MX NFS 30P OFF,4 - PROMOTION,NaN,409947,211.495587
263664,TIENDA 1,9/30/2018 0:00,95006,8.880000e+11,994341-ATI,M,APPAREL,RUNNING,MENS,549.0,1,331.293103,53.006897,384.30,164.70,MX NFS 30P OFF,4 - PROMOTION,NaN,340843,211.495587
263665,TIENDA 1,9/30/2018 0:00,95017,8.880000e+11,146194-BTJ,L,APPAREL,RUNNING,MENS,599.0,1,464.741379,74.358621,539.10,59.90,MX NFS 10P OFF,4 - PROMOTION,NaN,318683,169.549059
263666,TIENDA 1,9/30/2018 0:00,26174,8.880000e+11,573867-VWD,S,APPAREL,RUNNING,MENS,799.0,1,385.724138,61.715862,447.44,351.56,Store Level Promotion,4 - PROMOTION,NaN,362045,306.476279
263667,TIENDA 1,9/30/2018 0:00,95018,8.880000e+11,573867-VWD,XL,APPAREL,RUNNING,MENS,799.0,1,385.724138,61.715862,447.44,351.56,Store Level Promotion,4 - PROMOTION,NaN,318683,306.476279
263668,TIENDA 1,9/30/2018 0:00,95075,8.880000e+11,572999-XRF,L,APPAREL,RUNNING,WOMENS,899.0,1,542.500000,86.800000,629.30,269.70,MX NFS 30P OFF,4 - PROMOTION,NaN,340843,357.164702
263669,TIENDA 1,9/30/2018 0:00,94928,8.880000e+11,662089-NRV,S,APPAREL,RUNNING,MENS,799.0,1,482.155172,77.144828,559.30,239.70,MX NFS 30P OFF,4 - PROMOTION,NaN,340843,313.309527
263670,TIENDA 1,9/30/2018 0:00,19329,8.880000e+11,215145-ARI,M,APPAREL,RUNNING,MENS,599.0,1,361.465517,57.834483,419.30,179.70,MX NFS 30P OFF,4 - PROMOTION,NaN,312652,230.013835
263671,TIENDA 1,9/30/2018 0:00,19305,8.880000e+11,215145-ARI,L,APPAREL,RUNNING,MENS,599.0,1,361.465517,57.834483,419.30,179.70,MX NFS 30P OFF,4 - PROMOTION,NaN,312652,230.013835
263672,TIENDA 1,9/30/2018 0:00,95080,8.880000e+11,662114-GRO,S,APPAREL,RUNNING,MENS,899.0,1,542.500000,86.800000,629.30,269.70,MX NFS 30P OFF,4 - PROMOTION,NaN,340843,297.297289
263673,TIENDA 1,9/30/2018 0:00,3111,8.880000e+11,662114-GRO,S,APPAREL,RUNNING,MENS,899.0,1,542.500000,86.800000,629.30,269.70,MX NFS 30P OFF,4 - PROMOTION,NaN,269303,297.297289
263674,TIENDA 1,9/30/2018 0:00,19309,8.880000e+11,573048-IRQ,S,APPAREL,RUNNING,MENS,749.0,1,451.982759,72.317241,524.30,224.70,MX NFS 30P OFF,4 - PROMOTION,NaN,312652,298.331746
263675,TIENDA 1,9/30/2018 0:00,95070,8.880000e+11,573048-IRQ,M,APPAREL,RUNNING,MENS,749.0,1,451.982759,72.317241,524.30,224.70,MX NFS 30P OFF,4 - PROMOTION,NaN,340843,298.331746
263676,TIENDA 1,9/30/2018 0:00,3111,8.880000e+11,573048-IRQ,M,APPAREL,RUNNING,MENS,749.0,1,451.982759,72.317241,524.30,224.70,MX NFS 30P OFF,4 - PROMOTION,NaN,269303,298.331746
263677,TIENDA 1,9/30/2018 0:00,19281,8.880000e+11,573048-IRQ,L,APPAREL,RUNNING,MENS,749.0,1,451.982759,72.317241,524.30,224.70,MX NFS 30P OFF,4 - PROMOTION,NaN,312652,298.331746
263678,TIENDA 1,9/30/2018 0:00,26133,8.880000e+11,573048-IRQ,L,APPAREL,RUNNING,MENS,749.0,1,451.982759,72.317241,524.30,224.70,MX NFS 30P OFF,4 - PROMOTION,NaN,362045,298.331746
263679,TIENDA 1,9/30/2018 0:00,19302,8.880000e+11,573202-YSG,M,APPAREL,RUNNING,WOMENS,649.0,1,391.637931,62.662069,454.30,194.70,MX NFS 30P OFF,4 - PROMOTION,NaN,312652,272.703423
263680,TIENDA 1,9/30/2018 0:00,26111,8.880000e+11,573657-LUT,M,APPAREL,RUNNING,WOMENS,799.0,1,385.724138,61.715862,447.44,351.56,Store Level Promotion,4 - PROMOTION,NaN,362045,219.348722
263681,TIENDA 1,9/30/2018 0:00,19384,8.880000e+11,662699-TWB,7,FOOTWEAR,NIKE SPORTSWEAR,MENS,1799.0,1,868.482759,138.957241,1007.44,791.56,Store Level Promotion,4 - PROMOTION,NaN,312652,541.531273
263682,TIENDA 1,9/30/2018 0:00,3142,8.880000e+11,662829-TXB,S,APPAREL,FOOTBALL/SOCCER,MENS,1099.0,1,371.379310,59.420690,430.80,668.20,Store Level Promotion,4 - PROMOTION,NaN,269303,475.442545
263683,TIENDA 1,9/30/2018 0:00,26164,8.890000e+11,164064-KKS,S,APPAREL,NIKE SPORTSWEAR,WOMENS,2699.0,1,1302.965517,208.474483,1511.44,1187.56,Store Level Promotion,4 - PROMOTION,NaN,362045,1379.849891
263684,TIENDA 1,9/30/2018 0:00,95090,8.890000e+11,327345-HOP,XL,APPAREL,BASKETBALL,MENS,379.0,1,228.706897,36.593103,265.30,113.70,MX NFS 30P OFF,4 - PROMOTION,NaN,340843,561.011130
263685,TIENDA 1,9/30/2018 0:00,3075,8.890000e+11,164436-IOQ,M,APPAREL,BASKETBALL,MENS,379.0,1,228.706897,36.593103,265.30,113.70,MX NFS 30P OFF,4 - PROMOTION,NaN,269303,143.935306
263686,TIENDA 1,9/30/2018 0:00,26174,8.890000e+11,164436-IOQ,M,APPAREL,BASKETBALL,MENS,379.0,1,228.706897,36.593103,265.30,113.70,MX NFS 30P OFF,4 - PROMOTION,NaN,362045,143.935306

In [4]:
quality_report(dataset_original)

,Data type,missing values,present values,unique values,minimum values,maximun values
Store,object,0,263687,1,TIENDA 1,TIENDA 1
Date,object,0,263687,377,1/10/2018 0:00,9/9/2018 0:00
No_Tran,int64,0,263687,56726,1,99999
UPC,float64,0,263687,3112,0,8.89e+11
Material,object,228,263459,6013,NaN,NaN
Size,object,364,263323,120,NaN,NaN
Division,object,364,263323,3,NaN,NaN
Global Category,object,364,263323,9,NaN,NaN
Gender,object,364,263323,19,NaN,NaN
Public Price,float64,0,263687,2229,-5278.8,71358
Units,int64,0,263687,44,-19,74
Sale Price Wo tax,float64,0,263687,12751,-4550.69,61515.5
Tax,float64,0,263687,12792,-728.11,9842.48
Sale Price,float64,0,263687,12643,-5278.8,71358
Discount,float64,0,263687,11846,-1707.5,27267.6
Promo,object,0,263687,115,,VIP NOVIEMBRE 2017
Sales Type,object,0,263687,6,1 - NORMAL,6 - COMPLEMENTARY
Emp No,object,256949,6738,396,NaN,NaN
Sales Man,int64,0,263687,61,163868,777666
TTL Cost,float64,0,263687,8793,-6150.33,30971.4

In [14]:
dataset_nuevo=dataset_original[['Material', 'Units', 'Date']]

In [8]:
dataset_nuevo

          Material  Units            Date
0       146124-VQD      1   9/1/2017 0:00
1       662009-ZQH      1   9/1/2017 0:00
2       990552-HCP      1   9/1/2017 0:00
3       990552-HCP      1   9/1/2017 0:00
4       990552-HCP     -1   9/1/2017 0:00
5       990552-HCP      1   9/1/2017 0:00
6       990552-HCP      1   9/1/2017 0:00
7       990552-HCP      1   9/1/2017 0:00
8       662014-IQQ      1   9/1/2017 0:00
9       327277-NNV      1   9/1/2017 0:00
10      659994-MAU     -1   9/1/2017 0:00
11      659994-MAU      1   9/1/2017 0:00
12      212577-XEF      1   9/1/2017 0:00
13      212577-XEF      2   9/1/2017 0:00
14      212577-XEF      2   9/1/2017 0:00
15      212577-XEF      1   9/1/2017 0:00
16      212577-XEF     -2   9/1/2017 0:00
17      212577-XEF      1   9/1/2017 0:00
18      212577-XEF      1   9/1/2017 0:00
19      212577-XEF      1   9/1/2017 0:00
20      212577-XEF      1   9/1/2017 0:00
21      212577-XEF     -1   9/1/2017 0:00
22      163605-LET      1   9/1/2017 0:00
23      660689-PGX     -1   9/1/2017 0:00
24      660689-PGX      1   9/1/2017 0:00
25      660689-PGX      1   9/1/2017 0:00
26      760862-QGY     -1   9/1/2017 0:00
27      163518-KCS      1   9/1/2017 0:00
28      163518-KCS      1   9/1/2017 0:00
29      163518-KCS      1   9/1/2017 0:00
...            ...    ...             ...
263657  661984-GQO      1  9/30/2018 0:00
263658  661984-GQO      1  9/30/2018 0:00
263659  661984-GQO      1  9/30/2018 0:00
263660  762578-QRY      1  9/30/2018 0:00
263661  215577-STA      1  9/30/2018 0:00
263662  454287-YNG      1  9/30/2018 0:00
263663  994341-ATI      1  9/30/2018 0:00
263664  994341-ATI      1  9/30/2018 0:00
263665  146194-BTJ      1  9/30/2018 0:00
263666  573867-VWD      1  9/30/2018 0:00
263667  573867-VWD      1  9/30/2018 0:00
263668  572999-XRF      1  9/30/2018 0:00
263669  662089-NRV      1  9/30/2018 0:00
263670  215145-ARI      1  9/30/2018 0:00
263671  215145-ARI      1  9/30/2018 0:00
263672  662114-GRO      1  9/30/2018 0:00
263673  662114-GRO      1  9/30/2018 0:00
263674  573048-IRQ      1  9/30/2018 0:00
263675  573048-IRQ      1  9/30/2018 0:00
263676  573048-IRQ      1  9/30/2018 0:00
263677  573048-IRQ      1  9/30/2018 0:00
263678  573048-IRQ      1  9/30/2018 0:00
263679  573202-YSG      1  9/30/2018 0:00
263680  573657-LUT      1  9/30/2018 0:00
263681  662699-TWB      1  9/30/2018 0:00
263682  662829-TXB      1  9/30/2018 0:00
263683  164064-KKS      1  9/30/2018 0:00
263684  327345-HOP      1  9/30/2018 0:00
263685  164436-IOQ      1  9/30/2018 0:00
263686  164436-IOQ      1  9/30/2018 0:00

[263687 rows x 3 columns]

In [15]:
dataset_nuevo=dataset_nuevo.dropna()

In [10]:
dataset_nuevo

          Material  Units            Date
0       146124-VQD      1   9/1/2017 0:00
1       662009-ZQH      1   9/1/2017 0:00
2       990552-HCP      1   9/1/2017 0:00
3       990552-HCP      1   9/1/2017 0:00
4       990552-HCP     -1   9/1/2017 0:00
5       990552-HCP      1   9/1/2017 0:00
6       990552-HCP      1   9/1/2017 0:00
7       990552-HCP      1   9/1/2017 0:00
8       662014-IQQ      1   9/1/2017 0:00
9       327277-NNV      1   9/1/2017 0:00
10      659994-MAU     -1   9/1/2017 0:00
11      659994-MAU      1   9/1/2017 0:00
12      212577-XEF      1   9/1/2017 0:00
13      212577-XEF      2   9/1/2017 0:00
14      212577-XEF      2   9/1/2017 0:00
15      212577-XEF      1   9/1/2017 0:00
16      212577-XEF     -2   9/1/2017 0:00
17      212577-XEF      1   9/1/2017 0:00
18      212577-XEF      1   9/1/2017 0:00
19      212577-XEF      1   9/1/2017 0:00
20      212577-XEF      1   9/1/2017 0:00
21      212577-XEF     -1   9/1/2017 0:00
22      163605-LET      1   9/1/2017 0:00
23      660689-PGX     -1   9/1/2017 0:00
24      660689-PGX      1   9/1/2017 0:00
25      660689-PGX      1   9/1/2017 0:00
26      760862-QGY     -1   9/1/2017 0:00
27      163518-KCS      1   9/1/2017 0:00
28      163518-KCS      1   9/1/2017 0:00
29      163518-KCS      1   9/1/2017 0:00
...            ...    ...             ...
263657  661984-GQO      1  9/30/2018 0:00
263658  661984-GQO      1  9/30/2018 0:00
263659  661984-GQO      1  9/30/2018 0:00
263660  762578-QRY      1  9/30/2018 0:00
263661  215577-STA      1  9/30/2018 0:00
263662  454287-YNG      1  9/30/2018 0:00
263663  994341-ATI      1  9/30/2018 0:00
263664  994341-ATI      1  9/30/2018 0:00
263665  146194-BTJ      1  9/30/2018 0:00
263666  573867-VWD      1  9/30/2018 0:00
263667  573867-VWD      1  9/30/2018 0:00
263668  572999-XRF      1  9/30/2018 0:00
263669  662089-NRV      1  9/30/2018 0:00
263670  215145-ARI      1  9/30/2018 0:00
263671  215145-ARI      1  9/30/2018 0:00
263672  662114-GRO      1  9/30/2018 0:00
263673  662114-GRO      1  9/30/2018 0:00
263674  573048-IRQ      1  9/30/2018 0:00
263675  573048-IRQ      1  9/30/2018 0:00
263676  573048-IRQ      1  9/30/2018 0:00
263677  573048-IRQ      1  9/30/2018 0:00
263678  573048-IRQ      1  9/30/2018 0:00
263679  573202-YSG      1  9/30/2018 0:00
263680  573657-LUT      1  9/30/2018 0:00
263681  662699-TWB      1  9/30/2018 0:00
263682  662829-TXB      1  9/30/2018 0:00
263683  164064-KKS      1  9/30/2018 0:00
263684  327345-HOP      1  9/30/2018 0:00
263685  164436-IOQ      1  9/30/2018 0:00
263686  164436-IOQ      1  9/30/2018 0:00

[263459 rows x 3 columns]

In [19]:
quality_report(dataset_nuevo)

,Data type,missing values,present values,unique values,minimum values,maximun values
Material,object,0,257898,6005,145698-JAR,995880-FZN
Units,int64,0,257898,38,1,74
Date,object,0,257898,377,1/10/2018 0:00,9/9/2018 0:00

In [17]:
dataset_nuevo=dataset_nuevo[dataset_nuevo.Units>0]

In [125]:
quality_report(dataset_nuevo)

,Data type,missing values,present values,unique values,minimum values,maximun values
CODIGO,object,0,257898,6005,145698-JAR,995880-FZN
Units,int64,0,257898,38,1,74
Date,object,0,257898,377,1/10/2018 0:00,9/9/2018 0:00

In [21]:
dataset_nuevo.rename(columns={'Material':'CODIGO'}, inplace=True)

In [22]:
dataset_nuevo

            CODIGO  Units            Date
0       146124-VQD      1   9/1/2017 0:00
1       662009-ZQH      1   9/1/2017 0:00
2       990552-HCP      1   9/1/2017 0:00
3       990552-HCP      1   9/1/2017 0:00
5       990552-HCP      1   9/1/2017 0:00
6       990552-HCP      1   9/1/2017 0:00
7       990552-HCP      1   9/1/2017 0:00
8       662014-IQQ      1   9/1/2017 0:00
9       327277-NNV      1   9/1/2017 0:00
11      659994-MAU      1   9/1/2017 0:00
12      212577-XEF      1   9/1/2017 0:00
13      212577-XEF      2   9/1/2017 0:00
14      212577-XEF      2   9/1/2017 0:00
15      212577-XEF      1   9/1/2017 0:00
17      212577-XEF      1   9/1/2017 0:00
18      212577-XEF      1   9/1/2017 0:00
19      212577-XEF      1   9/1/2017 0:00
20      212577-XEF      1   9/1/2017 0:00
22      163605-LET      1   9/1/2017 0:00
24      660689-PGX      1   9/1/2017 0:00
25      660689-PGX      1   9/1/2017 0:00
27      163518-KCS      1   9/1/2017 0:00
28      163518-KCS      1   9/1/2017 0:00
29      163518-KCS      1   9/1/2017 0:00
30      163518-KCS      1   9/1/2017 0:00
31      453195-LCT      1   9/1/2017 0:00
32      453195-LCT      1   9/1/2017 0:00
33      453195-LCT      1   9/1/2017 0:00
34      990849-SEA      1   9/1/2017 0:00
35      990867-KES      1   9/1/2017 0:00
...            ...    ...             ...
263657  661984-GQO      1  9/30/2018 0:00
263658  661984-GQO      1  9/30/2018 0:00
263659  661984-GQO      1  9/30/2018 0:00
263660  762578-QRY      1  9/30/2018 0:00
263661  215577-STA      1  9/30/2018 0:00
263662  454287-YNG      1  9/30/2018 0:00
263663  994341-ATI      1  9/30/2018 0:00
263664  994341-ATI      1  9/30/2018 0:00
263665  146194-BTJ      1  9/30/2018 0:00
263666  573867-VWD      1  9/30/2018 0:00
263667  573867-VWD      1  9/30/2018 0:00
263668  572999-XRF      1  9/30/2018 0:00
263669  662089-NRV      1  9/30/2018 0:00
263670  215145-ARI      1  9/30/2018 0:00
263671  215145-ARI      1  9/30/2018 0:00
263672  662114-GRO      1  9/30/2018 0:00
263673  662114-GRO      1  9/30/2018 0:00
263674  573048-IRQ      1  9/30/2018 0:00
263675  573048-IRQ      1  9/30/2018 0:00
263676  573048-IRQ      1  9/30/2018 0:00
263677  573048-IRQ      1  9/30/2018 0:00
263678  573048-IRQ      1  9/30/2018 0:00
263679  573202-YSG      1  9/30/2018 0:00
263680  573657-LUT      1  9/30/2018 0:00
263681  662699-TWB      1  9/30/2018 0:00
263682  662829-TXB      1  9/30/2018 0:00
263683  164064-KKS      1  9/30/2018 0:00
263684  327345-HOP      1  9/30/2018 0:00
263685  164436-IOQ      1  9/30/2018 0:00
263686  164436-IOQ      1  9/30/2018 0:00

[257898 rows x 3 columns]

In [59]:
dataset_fecha=dataset_nuevo

In [39]:
dataset_fecha

            CODIGO  Units            Date
0       146124-VQD      1   9/1/2017 0:00
1       662009-ZQH      1   9/1/2017 0:00
2       990552-HCP      1   9/1/2017 0:00
3       990552-HCP      1   9/1/2017 0:00
5       990552-HCP      1   9/1/2017 0:00
6       990552-HCP      1   9/1/2017 0:00
7       990552-HCP      1   9/1/2017 0:00
8       662014-IQQ      1   9/1/2017 0:00
9       327277-NNV      1   9/1/2017 0:00
11      659994-MAU      1   9/1/2017 0:00
12      212577-XEF      1   9/1/2017 0:00
13      212577-XEF      2   9/1/2017 0:00
14      212577-XEF      2   9/1/2017 0:00
15      212577-XEF      1   9/1/2017 0:00
17      212577-XEF      1   9/1/2017 0:00
18      212577-XEF      1   9/1/2017 0:00
19      212577-XEF      1   9/1/2017 0:00
20      212577-XEF      1   9/1/2017 0:00
22      163605-LET      1   9/1/2017 0:00
24      660689-PGX      1   9/1/2017 0:00
25      660689-PGX      1   9/1/2017 0:00
27      163518-KCS      1   9/1/2017 0:00
28      163518-KCS      1   9/1/2017 0:00
29      163518-KCS      1   9/1/2017 0:00
30      163518-KCS      1   9/1/2017 0:00
31      453195-LCT      1   9/1/2017 0:00
32      453195-LCT      1   9/1/2017 0:00
33      453195-LCT      1   9/1/2017 0:00
34      990849-SEA      1   9/1/2017 0:00
35      990867-KES      1   9/1/2017 0:00
...            ...    ...             ...
263657  661984-GQO      1  9/30/2018 0:00
263658  661984-GQO      1  9/30/2018 0:00
263659  661984-GQO      1  9/30/2018 0:00
263660  762578-QRY      1  9/30/2018 0:00
263661  215577-STA      1  9/30/2018 0:00
263662  454287-YNG      1  9/30/2018 0:00
263663  994341-ATI      1  9/30/2018 0:00
263664  994341-ATI      1  9/30/2018 0:00
263665  146194-BTJ      1  9/30/2018 0:00
263666  573867-VWD      1  9/30/2018 0:00
263667  573867-VWD      1  9/30/2018 0:00
263668  572999-XRF      1  9/30/2018 0:00
263669  662089-NRV      1  9/30/2018 0:00
263670  215145-ARI      1  9/30/2018 0:00
263671  215145-ARI      1  9/30/2018 0:00
263672  662114-GRO      1  9/30/2018 0:00
263673  662114-GRO      1  9/30/2018 0:00
263674  573048-IRQ      1  9/30/2018 0:00
263675  573048-IRQ      1  9/30/2018 0:00
263676  573048-IRQ      1  9/30/2018 0:00
263677  573048-IRQ      1  9/30/2018 0:00
263678  573048-IRQ      1  9/30/2018 0:00
263679  573202-YSG      1  9/30/2018 0:00
263680  573657-LUT      1  9/30/2018 0:00
263681  662699-TWB      1  9/30/2018 0:00
263682  662829-TXB      1  9/30/2018 0:00
263683  164064-KKS      1  9/30/2018 0:00
263684  327345-HOP      1  9/30/2018 0:00
263685  164436-IOQ      1  9/30/2018 0:00
263686  164436-IOQ      1  9/30/2018 0:00

[257898 rows x 3 columns]

In [45]:
dataset_fecha

            CODIGO  Units            Date
0       146124-VQD      1   9/1/2017 0:00
1       662009-ZQH      1   9/1/2017 0:00
2       990552-HCP      1   9/1/2017 0:00
3       990552-HCP      1   9/1/2017 0:00
5       990552-HCP      1   9/1/2017 0:00
6       990552-HCP      1   9/1/2017 0:00
7       990552-HCP      1   9/1/2017 0:00
8       662014-IQQ      1   9/1/2017 0:00
9       327277-NNV      1   9/1/2017 0:00
11      659994-MAU      1   9/1/2017 0:00
12      212577-XEF      1   9/1/2017 0:00
13      212577-XEF      2   9/1/2017 0:00
14      212577-XEF      2   9/1/2017 0:00
15      212577-XEF      1   9/1/2017 0:00
17      212577-XEF      1   9/1/2017 0:00
18      212577-XEF      1   9/1/2017 0:00
19      212577-XEF      1   9/1/2017 0:00
20      212577-XEF      1   9/1/2017 0:00
22      163605-LET      1   9/1/2017 0:00
24      660689-PGX      1   9/1/2017 0:00
25      660689-PGX      1   9/1/2017 0:00
27      163518-KCS      1   9/1/2017 0:00
28      163518-KCS      1   9/1/2017 0:00
29      163518-KCS      1   9/1/2017 0:00
30      163518-KCS      1   9/1/2017 0:00
31      453195-LCT      1   9/1/2017 0:00
32      453195-LCT      1   9/1/2017 0:00
33      453195-LCT      1   9/1/2017 0:00
34      990849-SEA      1   9/1/2017 0:00
35      990867-KES      1   9/1/2017 0:00
...            ...    ...             ...
263657  661984-GQO      1  9/30/2018 0:00
263658  661984-GQO      1  9/30/2018 0:00
263659  661984-GQO      1  9/30/2018 0:00
263660  762578-QRY      1  9/30/2018 0:00
263661  215577-STA      1  9/30/2018 0:00
263662  454287-YNG      1  9/30/2018 0:00
263663  994341-ATI      1  9/30/2018 0:00
263664  994341-ATI      1  9/30/2018 0:00
263665  146194-BTJ      1  9/30/2018 0:00
263666  573867-VWD      1  9/30/2018 0:00
263667  573867-VWD      1  9/30/2018 0:00
263668  572999-XRF      1  9/30/2018 0:00
263669  662089-NRV      1  9/30/2018 0:00
263670  215145-ARI      1  9/30/2018 0:00
263671  215145-ARI      1  9/30/2018 0:00
263672  662114-GRO      1  9/30/2018 0:00
263673  662114-GRO      1  9/30/2018 0:00
263674  573048-IRQ      1  9/30/2018 0:00
263675  573048-IRQ      1  9/30/2018 0:00
263676  573048-IRQ      1  9/30/2018 0:00
263677  573048-IRQ      1  9/30/2018 0:00
263678  573048-IRQ      1  9/30/2018 0:00
263679  573202-YSG      1  9/30/2018 0:00
263680  573657-LUT      1  9/30/2018 0:00
263681  662699-TWB      1  9/30/2018 0:00
263682  662829-TXB      1  9/30/2018 0:00
263683  164064-KKS      1  9/30/2018 0:00
263684  327345-HOP      1  9/30/2018 0:00
263685  164436-IOQ      1  9/30/2018 0:00
263686  164436-IOQ      1  9/30/2018 0:00

[257898 rows x 3 columns]

In [60]:
dataset_fecha=dataset_fecha.join(dataset_fecha['Date'].str.split('/', 2, expand=True).rename(columns={0:'Mes', 1:'Dia', 2:'Año_'}))

In [61]:
dataset_fecha

            CODIGO  Units            Date Mes Dia       Año_
0       146124-VQD      1   9/1/2017 0:00   9   1  2017 0:00
1       662009-ZQH      1   9/1/2017 0:00   9   1  2017 0:00
2       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00
3       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00
5       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00
6       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00
7       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00
8       662014-IQQ      1   9/1/2017 0:00   9   1  2017 0:00
9       327277-NNV      1   9/1/2017 0:00   9   1  2017 0:00
11      659994-MAU      1   9/1/2017 0:00   9   1  2017 0:00
12      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00
13      212577-XEF      2   9/1/2017 0:00   9   1  2017 0:00
14      212577-XEF      2   9/1/2017 0:00   9   1  2017 0:00
15      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00
17      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00
18      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00
19      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00
20      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00
22      163605-LET      1   9/1/2017 0:00   9   1  2017 0:00
24      660689-PGX      1   9/1/2017 0:00   9   1  2017 0:00
25      660689-PGX      1   9/1/2017 0:00   9   1  2017 0:00
27      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00
28      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00
29      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00
30      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00
31      453195-LCT      1   9/1/2017 0:00   9   1  2017 0:00
32      453195-LCT      1   9/1/2017 0:00   9   1  2017 0:00
33      453195-LCT      1   9/1/2017 0:00   9   1  2017 0:00
34      990849-SEA      1   9/1/2017 0:00   9   1  2017 0:00
35      990867-KES      1   9/1/2017 0:00   9   1  2017 0:00
...            ...    ...             ...  ..  ..        ...
263657  661984-GQO      1  9/30/2018 0:00   9  30  2018 0:00
263658  661984-GQO      1  9/30/2018 0:00   9  30  2018 0:00
263659  661984-GQO      1  9/30/2018 0:00   9  30  2018 0:00
263660  762578-QRY      1  9/30/2018 0:00   9  30  2018 0:00
263661  215577-STA      1  9/30/2018 0:00   9  30  2018 0:00
263662  454287-YNG      1  9/30/2018 0:00   9  30  2018 0:00
263663  994341-ATI      1  9/30/2018 0:00   9  30  2018 0:00
263664  994341-ATI      1  9/30/2018 0:00   9  30  2018 0:00
263665  146194-BTJ      1  9/30/2018 0:00   9  30  2018 0:00
263666  573867-VWD      1  9/30/2018 0:00   9  30  2018 0:00
263667  573867-VWD      1  9/30/2018 0:00   9  30  2018 0:00
263668  572999-XRF      1  9/30/2018 0:00   9  30  2018 0:00
263669  662089-NRV      1  9/30/2018 0:00   9  30  2018 0:00
263670  215145-ARI      1  9/30/2018 0:00   9  30  2018 0:00
263671  215145-ARI      1  9/30/2018 0:00   9  30  2018 0:00
263672  662114-GRO      1  9/30/2018 0:00   9  30  2018 0:00
263673  662114-GRO      1  9/30/2018 0:00   9  30  2018 0:00
263674  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00
263675  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00
263676  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00
263677  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00
263678  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00
263679  573202-YSG      1  9/30/2018 0:00   9  30  2018 0:00
263680  573657-LUT      1  9/30/2018 0:00   9  30  2018 0:00
263681  662699-TWB      1  9/30/2018 0:00   9  30  2018 0:00
263682  662829-TXB      1  9/30/2018 0:00   9  30  2018 0:00
263683  164064-KKS      1  9/30/2018 0:00   9  30  2018 0:00
263684  327345-HOP      1  9/30/2018 0:00   9  30  2018 0:00
263685  164436-IOQ      1  9/30/2018 0:00   9  30  2018 0:00
263686  164436-IOQ      1  9/30/2018 0:00   9  30  2018 0:00

[257898 rows x 6 columns]

In [62]:
dataset_fecha=dataset_fecha.join(dataset_fecha['Año_'].str.split(' ', 1, expand=True).rename(columns={0:'Año',2:'hora'}))

In [63]:
dataset_fecha

            CODIGO  Units            Date Mes Dia       Año_   Año     1
0       146124-VQD      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
1       662009-ZQH      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
2       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
3       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
5       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
6       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
7       990552-HCP      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
8       662014-IQQ      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
9       327277-NNV      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
11      659994-MAU      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
12      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
13      212577-XEF      2   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
14      212577-XEF      2   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
15      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
17      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
18      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
19      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
20      212577-XEF      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
22      163605-LET      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
24      660689-PGX      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
25      660689-PGX      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
27      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
28      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
29      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
30      163518-KCS      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
31      453195-LCT      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
32      453195-LCT      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
33      453195-LCT      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
34      990849-SEA      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
35      990867-KES      1   9/1/2017 0:00   9   1  2017 0:00  2017  0:00
...            ...    ...             ...  ..  ..        ...   ...   ...
263657  661984-GQO      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263658  661984-GQO      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263659  661984-GQO      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263660  762578-QRY      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263661  215577-STA      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263662  454287-YNG      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263663  994341-ATI      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263664  994341-ATI      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263665  146194-BTJ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263666  573867-VWD      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263667  573867-VWD      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263668  572999-XRF      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263669  662089-NRV      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263670  215145-ARI      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263671  215145-ARI      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263672  662114-GRO      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263673  662114-GRO      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263674  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263675  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263676  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263677  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263678  573048-IRQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263679  573202-YSG      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263680  573657-LUT      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263681  662699-TWB      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263682  662829-TXB      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263683  164064-KKS      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263684  327345-HOP      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263685  164436-IOQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00
263686  164436-IOQ      1  9/30/2018 0:00   9  30  2018 0:00  2018  0:00

[257898 rows x 8 columns]

In [64]:
dataset_fecha=dataset_fecha[['CODIGO', 'Units', 'Mes', 'Dia','Año']]

In [67]:
quality_report(dataset_fecha)

,Data type,missing values,present values,unique values,minimum values,maximun values
CODIGO,object,0,257898,6005,145698-JAR,995880-FZN
Units,int64,0,257898,38,1,74
Mes,object,0,257898,12,1,9
Dia,object,0,257898,31,1,9
Año,object,0,257898,2,2017,2018

In [69]:
dataset_tabla=dataset_fecha.pivot_table('Units', ['CODIGO', 'Año'], columns= 'Mes', aggfunc= np.sum)

In [79]:
dataset_tabla=dataset_tabla.fillna(0)

In [80]:
dataset_tabla = dataset_tabla.rename(columns = {1:'ENE.',2:'FEB.',3:'MAR.',4:'ABR.',5:'MAY.',6:'JUN.',7:'JUL.',8:'AGO.',9:'SEP',10:'OCT.',11:'NOV.',12:'DIC.'})

In [81]:
dataset_tabla

Mes                  1    10    11    12     2     3     4     5     6     7  \
CODIGO     Año
145698-JAR 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145699-SAA 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145700-BAJ 2018   99.0   0.0   0.0   0.0   2.0   2.0   0.0   0.0   0.0   0.0
145701-KAS 2017    0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145702-TAB 2017    0.0  14.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145703-CAK 2017    0.0   1.0   7.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0
145704-LAT 2018    0.0   0.0   0.0   0.0  61.0  37.0   8.0   1.0   5.0   4.0
145705-UAC 2017    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145706-DAL 2017    0.0   0.0  35.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145707-MAU 2017    0.0   9.0  25.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0
145708-VAD 2017    0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145709-EAM 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
145710-NAV 2017    0.0   1.0   3.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    0.0   0.0   0.0   0.0   2.0   1.0   4.0   6.0   6.0   4.0
145711-WAE 2018    0.0   0.0   0.0   0.0   0.0   6.0   0.0   0.0   0.0   0.0
145712-FAN 2017    0.0   1.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0
145713-OAW 2018    0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0
145714-XAF 2017    0.0   0.0  43.0  61.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    2.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0
145715-GAO 2017    0.0   0.0  18.0  74.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    2.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0   1.0   0.0
145716-PAX 2018    0.0   0.0   0.0   0.0  12.0   9.0   0.0   0.0   0.0   0.0
145717-YAG 2018    0.0   0.0   0.0   0.0  96.0   4.0   0.0   0.0  10.0  40.0
145718-HAP 2018    0.0   0.0   0.0   0.0   5.0   1.0  23.0  39.0   8.0   6.0
145719-QAY 2017    0.0   3.0  24.0   6.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    7.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0   7.0
145720-ZAH 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
...                ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
995691-YZG 2018    1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0
995700-HZP 2018    3.0   0.0   0.0   0.0  34.0  47.0  33.0  17.0   0.0   0.0
995709-QZY 2018    4.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0   0.0
995718-ZZH 2017    0.0   3.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   2.0
995727-IZQ 2017    0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
995736-RZZ 2017    0.0   3.0  10.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    3.0   0.0   0.0   0.0   0.0   0.0   5.0   1.0   1.0   1.0
995745-AZI 2017    0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
995754-JZR 2017    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
995763-SZA 2017    0.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
995772-BZJ 2017    0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    9.0   0.0   0.0   0.0   1.0   8.0   0.0   0.0   0.0   1.0
995781-KZS 2017    0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    4.0   0.0   0.0   0.0   0.0   0.0   3.0   4.0   2.0   5.0
995790-TZB 2017    0.0   0.0   0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018  137.0   0.0   0.0   0.0  79.0  94.0  14.0  42.0  15.0  45.0
995799-CZK 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   1.0   2.0
995808-LZT 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
995817-UZC 2017    0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    0.0   0.0   0.0   0.0   0.0   2.0   2.0   4.0   2.0   2.0
995826-DZL 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  23.0
995835-MZU 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
995844-VZD 2017    0.0   0.0   0.0   9.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018   10.0   0.0   0.0   0.0   2.0   3.0   4.0   4.0   0.0   2.0
995853-EZM 2018    0.0   0.0   0.0   0.0  60.0   0.0   0.0   0.0   0.0   0.0
995862-NZV 2017    0.0   0.0   0.0  16.0   0.0   0.0   0.0   0.0   0.0   0.0
           2018    6.0   0.0   0.0   0.0   0.0   1.0   4.0   2.0   0.0   0.0
995871-WZE 2018   30.0   0.0   0.0   0.0  49.0   0.0   0.0   0.0   0.0   0.0
995880-FZN 2018    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0

Mes                  8      9
CODIGO     Año
145698-JAR 2018    0.0    1.0
145699-SAA 2018    8.0    1.0
145700-BAJ 2018    0.0    0.0
145701-KAS 2017    0.0    0.0
145702-TAB 2017    0.0    0.0
145703-CAK 2017    0.0    0.0
           2018    0.0    0.0
145704-LAT 2018    0.0    0.0
145705-UAC 2017    0.0    1.0
145706-DAL 2017    0.0    0.0
145707-MAU 2017    0.0   16.0
145708-VAD 2017    0.0    2.0
           2018    0.0    0.0
145709-EAM 2018    0.0    1.0
145710-NAV 2017    0.0    1.0
           2018    0.0    0.0
145711-WAE 2018    0.0    0.0
145712-FAN 2017    0.0    0.0
           2018    0.0    0.0
145713-OAW 2018    0.0    0.0
145714-XAF 2017    0.0    0.0
           2018    0.0    0.0
145715-GAO 2017    0.0    0.0
           2018    0.0    0.0
145716-PAX 2018    0.0    0.0
145717-YAG 2018   50.0    0.0
145718-HAP 2018    0.0    0.0
145719-QAY 2017    0.0    8.0
           2018    8.0    4.0
145720-ZAH 2018  103.0   96.0
...                ...    ...
995691-YZG 2018    0.0    0.0
995700-HZP 2018    0.0    0.0
995709-QZY 2018    0.0    0.0
995718-ZZH 2017    0.0    1.0
           2018    0.0    0.0
995727-IZQ 2017    0.0    0.0
995736-RZZ 2017    0.0    1.0
           2018    0.0    0.0
995745-AZI 2017    0.0    3.0
995754-JZR 2017    0.0    1.0
995763-SZA 2017    0.0    2.0
995772-BZJ 2017    0.0    0.0
           2018    0.0    4.0
995781-KZS 2017    0.0    0.0
           2018    2.0    0.0
995790-TZB 2017    0.0    0.0
           2018   51.0   29.0
995799-CZK 2018    1.0    2.0
995808-LZT 2018    0.0    1.0
995817-UZC 2017    0.0    0.0
           2018    3.0    2.0
995826-DZL 2018   15.0    3.0
995835-MZU 2018    0.0  143.0
995844-VZD 2017    0.0    0.0
           2018    4.0    1.0
995853-EZM 2018    0.0    0.0
995862-NZV 2017    0.0    0.0
           2018    0.0    0.0
995871-WZE 2018    0.0   63.0
995880-FZN 2018    4.0    2.0

[7877 rows x 12 columns]

In [149]:
datatable=dataset_tabla

In [150]:
datatable=datatable.reset_index()

In [151]:
datatable

Mes,CODIGO,Año,1,10,11,12,2,3,4,5,6,7,8,9
0,145698-JAR,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,145699-SAA,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0
2,145700-BAJ,2018,99.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,145701-KAS,2017,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,145702-TAB,2017,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,145703-CAK,2017,0.0,1.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,145703-CAK,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
7,145704-LAT,2018,0.0,0.0,0.0,0.0,61.0,37.0,8.0,1.0,5.0,4.0,0.0,0.0
8,145705-UAC,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,145706-DAL,2017,0.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,145707-MAU,2017,0.0,9.0,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0
11,145708-VAD,2017,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
12,145708-VAD,2018,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,145709-EAM,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,145710-NAV,2017,0.0,1.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,145710-NAV,2018,0.0,0.0,0.0,0.0,2.0,1.0,4.0,6.0,6.0,4.0,0.0,0.0
16,145711-WAE,2018,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
17,145712-FAN,2017,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,145712-FAN,2018,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,145713-OAW,2018,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,145714-XAF,2017,0.0,0.0,43.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,145714-XAF,2018,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,145715-GAO,2017,0.0,0.0,18.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,145715-GAO,2018,2.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0
24,145716-PAX,2018,0.0,0.0,0.0,0.0,12.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0
25,145717-YAG,2018,0.0,0.0,0.0,0.0,96.0,4.0,0.0,0.0,10.0,40.0,50.0,0.0
26,145718-HAP,2018,0.0,0.0,0.0,0.0,5.0,1.0,23.0,39.0,8.0,6.0,0.0,0.0
27,145719-QAY,2017,0.0,3.0,24.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
28,145719-QAY,2018,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7.0,8.0,4.0
29,145720-ZAH,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103.0,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,995691-YZG,2018,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7848,995700-HZP,2018,3.0,0.0,0.0,0.0,34.0,47.0,33.0,17.0,0.0,0.0,0.0,0.0
7849,995709-QZY,2018,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
7850,995718-ZZH,2017,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7851,995718-ZZH,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0
7852,995727-IZQ,2017,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7853,995736-RZZ,2017,0.0,3.0,10.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7854,995736-RZZ,2018,3.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,1.0,1.0,0.0,0.0
7855,995745-AZI,2017,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
7856,995754-JZR,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7857,995763-SZA,2017,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
7858,995772-BZJ,2017,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7859,995772-BZJ,2018,9.0,0.0,0.0,0.0,1.0,8.0,0.0,0.0,0.0,1.0,0.0,4.0
7860,995781-KZS,2017,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7861,995781-KZS,2018,4.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,2.0,5.0,2.0,0.0
7862,995790-TZB,2017,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7863,995790-TZB,2018,137.0,0.0,0.0,0.0,79.0,94.0,14.0,42.0,15.0,45.0,51.0,29.0
7864,995799-CZK,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0,1.0,2.0
7865,995808-LZT,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7866,995817-UZC,2017,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7867,995817-UZC,2018,0.0,0.0,0.0,0.0,0.0,2.0,2.0,4.0,2.0,2.0,3.0,2.0
7868,995826-DZL,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,23.0,15.0,3.0
7869,995835-MZU,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0
7870,995844-VZD,2017,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7871,995844-VZD,2018,10.0,0.0,0.0,0.0,2.0,3.0,4.0,4.0,0.0,2.0,4.0,1.0
7872,995853-EZM,2018,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7873,995862-NZV,2017,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7874,995862-NZV,2018,6.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,0.0,0.0,0.0,0.0
7875,995871-WZE,2018,30.0,0.0,0.0,0.0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0
7876,995880-FZN,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0

In [152]:
datatable = datatable.rename(columns = {'1':'ENE.','2':'FEB.','3':'MAR.','4':'ABR.','5':'MAY.','6':'JUN.','7':'JUL.','8':'AGO.','9':'SEP.','10':'OCT.','11':'NOV.','12':'DIC.'})

In [153]:
datatable

Mes,CODIGO,Año,ENE.,OCT.,NOV.,DIC.,FEB.,MAR.,ABR.,MAY.,JUN.,JUL.,AGO.,SEP.
0,145698-JAR,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,145699-SAA,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0
2,145700-BAJ,2018,99.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,145701-KAS,2017,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,145702-TAB,2017,0.0,14.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,145703-CAK,2017,0.0,1.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,145703-CAK,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
7,145704-LAT,2018,0.0,0.0,0.0,0.0,61.0,37.0,8.0,1.0,5.0,4.0,0.0,0.0
8,145705-UAC,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,145706-DAL,2017,0.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,145707-MAU,2017,0.0,9.0,25.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0
11,145708-VAD,2017,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
12,145708-VAD,2018,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,145709-EAM,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,145710-NAV,2017,0.0,1.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,145710-NAV,2018,0.0,0.0,0.0,0.0,2.0,1.0,4.0,6.0,6.0,4.0,0.0,0.0
16,145711-WAE,2018,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
17,145712-FAN,2017,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,145712-FAN,2018,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,145713-OAW,2018,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,145714-XAF,2017,0.0,0.0,43.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,145714-XAF,2018,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,145715-GAO,2017,0.0,0.0,18.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,145715-GAO,2018,2.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0
24,145716-PAX,2018,0.0,0.0,0.0,0.0,12.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0
25,145717-YAG,2018,0.0,0.0,0.0,0.0,96.0,4.0,0.0,0.0,10.0,40.0,50.0,0.0
26,145718-HAP,2018,0.0,0.0,0.0,0.0,5.0,1.0,23.0,39.0,8.0,6.0,0.0,0.0
27,145719-QAY,2017,0.0,3.0,24.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
28,145719-QAY,2018,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7.0,8.0,4.0
29,145720-ZAH,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103.0,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,995691-YZG,2018,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7848,995700-HZP,2018,3.0,0.0,0.0,0.0,34.0,47.0,33.0,17.0,0.0,0.0,0.0,0.0
7849,995709-QZY,2018,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
7850,995718-ZZH,2017,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7851,995718-ZZH,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0
7852,995727-IZQ,2017,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7853,995736-RZZ,2017,0.0,3.0,10.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7854,995736-RZZ,2018,3.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,1.0,1.0,0.0,0.0
7855,995745-AZI,2017,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
7856,995754-JZR,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7857,995763-SZA,2017,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
7858,995772-BZJ,2017,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7859,995772-BZJ,2018,9.0,0.0,0.0,0.0,1.0,8.0,0.0,0.0,0.0,1.0,0.0,4.0
7860,995781-KZS,2017,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7861,995781-KZS,2018,4.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,2.0,5.0,2.0,0.0
7862,995790-TZB,2017,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7863,995790-TZB,2018,137.0,0.0,0.0,0.0,79.0,94.0,14.0,42.0,15.0,45.0,51.0,29.0
7864,995799-CZK,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0,1.0,2.0
7865,995808-LZT,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7866,995817-UZC,2017,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7867,995817-UZC,2018,0.0,0.0,0.0,0.0,0.0,2.0,2.0,4.0,2.0,2.0,3.0,2.0
7868,995826-DZL,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,23.0,15.0,3.0
7869,995835-MZU,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0
7870,995844-VZD,2017,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7871,995844-VZD,2018,10.0,0.0,0.0,0.0,2.0,3.0,4.0,4.0,0.0,2.0,4.0,1.0
7872,995853-EZM,2018,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7873,995862-NZV,2017,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7874,995862-NZV,2018,6.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,0.0,0.0,0.0,0.0
7875,995871-WZE,2018,30.0,0.0,0.0,0.0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0
7876,995880-FZN,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0

In [154]:
 datatable2 = datatable[['CODIGO', 'Año', 'ENE.', 'FEB.', 'MAR.', 'ABR.', 'MAY.','JUN.', 'JUL.', 'AGO.', 'SEP.', 'OCT.', 'NOV.','DIC.']]

In [155]:
datatable2

Mes,CODIGO,Año,ENE.,FEB.,MAR.,ABR.,MAY.,JUN.,JUL.,AGO.,SEP.,OCT.,NOV.,DIC.
0,145698-JAR,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,145699-SAA,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0
2,145700-BAJ,2018,99.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,145701-KAS,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,145702-TAB,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,4.0,0.0
5,145703-CAK,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7.0,1.0
6,145703-CAK,2018,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
7,145704-LAT,2018,0.0,61.0,37.0,8.0,1.0,5.0,4.0,0.0,0.0,0.0,0.0,0.0
8,145705-UAC,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,145706-DAL,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0
10,145707-MAU,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,9.0,25.0,2.0
11,145708-VAD,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0
12,145708-VAD,2018,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,145709-EAM,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,145710-NAV,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,4.0
15,145710-NAV,2018,0.0,2.0,1.0,4.0,6.0,6.0,4.0,0.0,0.0,0.0,0.0,0.0
16,145711-WAE,2018,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,145712-FAN,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0
18,145712-FAN,2018,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,145713-OAW,2018,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,145714-XAF,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0,61.0
21,145714-XAF,2018,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,145715-GAO,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,74.0
23,145715-GAO,2018,2.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
24,145716-PAX,2018,0.0,12.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,145717-YAG,2018,0.0,96.0,4.0,0.0,0.0,10.0,40.0,50.0,0.0,0.0,0.0,0.0
26,145718-HAP,2018,0.0,5.0,1.0,23.0,39.0,8.0,6.0,0.0,0.0,0.0,0.0,0.0
27,145719-QAY,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,3.0,24.0,6.0
28,145719-QAY,2018,7.0,0.0,0.0,0.0,0.0,2.0,7.0,8.0,4.0,0.0,0.0,0.0
29,145720-ZAH,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103.0,96.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7847,995691-YZG,2018,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7848,995700-HZP,2018,3.0,34.0,47.0,33.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7849,995709-QZY,2018,4.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7850,995718-ZZH,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,3.0,0.0
7851,995718-ZZH,2018,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
7852,995727-IZQ,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7853,995736-RZZ,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,10.0,1.0
7854,995736-RZZ,2018,3.0,0.0,0.0,5.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
7855,995745-AZI,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,0.0
7856,995754-JZR,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7857,995763-SZA,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0
7858,995772-BZJ,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7859,995772-BZJ,2018,9.0,1.0,8.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0
7860,995781-KZS,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7861,995781-KZS,2018,4.0,0.0,0.0,3.0,4.0,2.0,5.0,2.0,0.0,0.0,0.0,0.0
7862,995790-TZB,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
7863,995790-TZB,2018,137.0,79.0,94.0,14.0,42.0,15.0,45.0,51.0,29.0,0.0,0.0,0.0
7864,995799-CZK,2018,0.0,0.0,0.0,0.0,4.0,1.0,2.0,1.0,2.0,0.0,0.0,0.0
7865,995808-LZT,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7866,995817-UZC,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
7867,995817-UZC,2018,0.0,0.0,2.0,2.0,4.0,2.0,2.0,3.0,2.0,0.0,0.0,0.0
7868,995826-DZL,2018,0.0,0.0,0.0,0.0,0.0,2.0,23.0,15.0,3.0,0.0,0.0,0.0
7869,995835-MZU,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0,0.0,0.0,0.0
7870,995844-VZD,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
7871,995844-VZD,2018,10.0,2.0,3.0,4.0,4.0,0.0,2.0,4.0,1.0,0.0,0.0,0.0
7872,995853-EZM,2018,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7873,995862-NZV,2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0
7874,995862-NZV,2018,6.0,0.0,1.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7875,995871-WZE,2018,30.0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0,0.0,0.0,0.0
7876,995880-FZN,2018,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,2.0,0.0,0.0,0.0

In [156]:
quality_report(datatable2)

,Data type,missing values,present values,unique values,minimum values,maximun values
Mes,,,,,,
CODIGO,object,0,7877,6005,145698-JAR,995880-FZN
Año,object,0,7877,2,2017,2018
ENE.,float64,0,7877,118,0,155
FEB.,float64,0,7877,99,0,169
MAR.,float64,0,7877,94,0,148
ABR.,float64,0,7877,94,0,191
MAY.,float64,0,7877,91,0,123
JUN.,float64,0,7877,56,0,88
JUL.,float64,0,7877,71,0,106
AGO.,float64,0,7877,77,0,136
SEP.,float64,0,7877,80,0,181
OCT.,float64,0,7877,48,0,90
NOV.,float64,0,7877,115,0,250
DIC.,float64,0,7877,121,0,173

In [157]:
datatable2.Año = datatable2.Año.astype(int)

In [158]:
quality_report(datatable2)

,Data type,missing values,present values,unique values,minimum values,maximun values
Mes,,,,,,
CODIGO,object,0,7877,6005,145698-JAR,995880-FZN
Año,int32,0,7877,2,2017,2018
ENE.,float64,0,7877,118,0,155
FEB.,float64,0,7877,99,0,169
MAR.,float64,0,7877,94,0,148
ABR.,float64,0,7877,94,0,191
MAY.,float64,0,7877,91,0,123
JUN.,float64,0,7877,56,0,88
JUL.,float64,0,7877,71,0,106
AGO.,float64,0,7877,77,0,136
SEP.,float64,0,7877,80,0,181
OCT.,float64,0,7877,48,0,90
NOV.,float64,0,7877,115,0,250
DIC.,float64,0,7877,121,0,173

In [163]:
datatable2['ENE.']= datatable2['ENE.'].astype(int)

In [164]:
datatable2['FEB.']= datatable2['FEB.'].astype(int)
datatable2['MAR.']= datatable2['MAR.'].astype(int)
datatable2['ABR.']= datatable2['ABR.'].astype(int)
datatable2['MAY.']= datatable2['MAY.'].astype(int)
datatable2['JUN.']= datatable2['JUN.'].astype(int)
datatable2['JUL.']= datatable2['JUL.'].astype(int)
datatable2['AGO.']= datatable2['AGO.'].astype(int)
datatable2['SEP.']= datatable2['SEP.'].astype(int)
datatable2['OCT.']= datatable2['OCT.'].astype(int)
datatable2['NOV.']= datatable2['NOV.'].astype(int)
datatable2['DIC.']= datatable2['DIC.'].astype(int)

In [165]:
quality_report(datatable2)

,Data type,missing values,present values,unique values,minimum values,maximun values
Mes,,,,,,
CODIGO,object,0,7877,6005,145698-JAR,995880-FZN
Año,int32,0,7877,2,2017,2018
ENE.,int32,0,7877,118,0,155
FEB.,int32,0,7877,99,0,169
MAR.,int32,0,7877,94,0,148
ABR.,int32,0,7877,94,0,191
MAY.,int32,0,7877,91,0,123
JUN.,int32,0,7877,56,0,88
JUL.,int32,0,7877,71,0,106
AGO.,int32,0,7877,77,0,136
SEP.,int32,0,7877,80,0,181
OCT.,int32,0,7877,48,0,90
NOV.,int32,0,7877,115,0,250
DIC.,int32,0,7877,121,0,173